# Generated by Django 3.1.5 on 2021-02-02 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, max_length=200, null=True)),
                ('article_keywords', models.TextField(blank=True, max_length=1000, null=True)),
                ('article_author', models.CharField(blank=True, max_length=100, null=True)),
                ('article_content', models.TextField(blank=True, max_length=12500, null=True)),
                ('article_image', models.ImageField(blank=True, null=True, unique=True, upload_to='ArticlesImages')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'articlesmodel',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category_description', models.CharField(blank=True, max_length=500, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categorymodel',
            },
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, max_length=1500, null=True)),
                ('status', models.CharField(blank=True, default='Unread', max_length=20, null=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificationmodel',
            },
        ),
        migrations.CreateModel(
            name='UnApprovedUsersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('sign_up_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'unapprovedusersmodel',
            },
        ),
        migrations.CreateModel(
            name='ViewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsection.articlesmodel', verbose_name='article view')),
            ],
            options={
                'db_table': 'viewsmodel',
            },
        ),
    ]
